---
title: Promise
date: 2021-04-21 09:46:23
permalink: /pages/d57563/
categories:
  - 前端
tags:
  - JavaScript
  - 异步编程
---
## 前言
Promise 是 ES6 引入的异步编程方案，能有效解决回调地狱问题。简单来说，Promise 是一个对象，保存着未来才会结束的事件，并提供统一的 API 供使用者处理异步操作。

## 创建
### new Promise()
Promise 构造函数接受函数作为参数，该函数参数为 resolve 和 reject。通过 new Promise() 来创建 promise 对象最为常见
```js
const promise = new Promise(function (resolve, reject) {
  // 一些操作后会调用 resolve 或 reject
  if (/* 一些判断 */) {
    resolve(someValue) // fulfilled 状态，并返回值
  } else {
    reject(/* 失败原因 */) // rejected 状态
  }
});
```
新生成的 promise 对象会处于 pending(进行中) 状态，后面根据执行结果进入 fulfilled（已成功）或 reject（已失败）状态

### Promise.resolve()
```js
Promise.resolve(1).then(function (value) {
  console.log(value); // 1
});
```
这种形式的 promise 对象已经是 resolve 状态，并将参数传递到 then 所指定的 onFulfilled 函数

### Promise.reject()
```js
Promise.reject(new Error('进入 rejected 状态'));
```

## Promise 解决回调地狱
先看一下回调地狱
```js
let fs = require('fs')
fs.readFile('./a.txt','utf8', function (err, data) {
  fs.readFile(data, 'utf8', function (err, data) {
    fs.readFile(data, 'utf8', function (err, data) {
      console.log(data)
    })
  })
})
```
缺点：
- 代码嵌套多层，不直观
- 每个人物需要分贝处理成功和失败两种可能性

使用 Promise 来看看
```js
let fs = require('fs')
function read (url) {
  return new Promise((resolve,reject) => {
    fs.readFile(url, 'utf8', function (err, data) {
      err && reject(err)
      resolve(data)
    })
  })
}
read('./a.txt').then(data => {
  return read(data)
}).then(data => {
  return read(data)
}).then(data => {
  console.log(data)
})
```
看起来就简洁了不少，很好地解决了回调地狱，它是怎么解决的呢？

首先解决嵌套多层，Promise 采用回调函数延迟绑定和

### 回调函数延迟绑定
从上面例子中看出回调函数是 read.then() 中传递的，而不是在声明 read 时传入的，这样的延迟传入，

## API
### Promise.then()
- 会返回一个新的 Promise
- promise 状态变更后，后续的 then 都可以获取到这个值
- 返回值不能是 promise 自身，否则会造成死循环
- then 中 return 一个错误不会抛出作物，所以不会被后续 .catch 获取
- 参数期望是函数，传入非函数会造成值穿透
- 接收两个参数
  - resolve 处理成功
  - reject 处理失败

### Promise.catch()
- catch 会返回一个新 Promise
- catch 不管连接在哪里都会回去上层未捕捉过的错误
- promise 状态变更后，后续的 catch 都可以获取到这个值
- catch 中 return 一个错误不会抛出作物，所以不会被后续 .catch 获取
- 返回值不能是 promise 自身，否则会造成死循环
- 参数期望是函数，传入非函数会造成值穿透

### Promise.finally()
- 不管 Promise 对象最后的状态如何都会执行
- 回调函数不接受任何的参数，也就是说你在 .finally() 函数中是没法知道 Promise 最终的状态是 resolved 还是 rejected 的
- 最终返回的默认会是一个上一次的 Promise 对象值，不过如果抛出的是一个异常则返回异常的 Promise 对象

### Promise.all()
- 接收一组异步任务
- 然后并行执行异步任务
- 所有任务执行完毕后才会执行回调

### Promise.race()
- 接收一组异步任务
- 然后并行执行异步任务
- 保留第一个执行完成的异步操作结果
- 其他的方法仍在执行，不过结果会被抛弃

## promise 实现
```js
const PENDING = 'pending';
const FULFILLED = 'fulfilled';
const REJECTED = 'rejected';

class Promise {
  constructor (executor) {
    this.status = PENDING;
    this.value = undefined;
    this.reason = undefined;

    this.onFulfilledCallbacks = [];
    this.onRejectedCallbacks = [];

    const resolve = value => {
      if (value instanceof Promise) return value.then(resolve, reject);
      if (this.status === PENDING) {
        setTimeout(() => {
          this.status = FULFILLED;
          this.value = value;
          this.onFulfilledCallbacks = [];
        })
      }
    }

    const reject = error => {
      if (this.status === PENDING) {
        setTimeout(() => {
          this.status = REJECTED;
          this.reason = reason;
          this.onRejectedCallbacks = [];
        });
      }
    }

    try {
      executor(resolve, reject);
    } catch (e) {
      reject(e);
    }
  }

  then (onFulfilled, onRejected) {
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
    onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw new Error(reason instanceof Error ? reason.message : reason )};

    const self = this;
    return new Promise((resolve, reject) => {
      if (self.status === PENDING) {
        self.onFulfilledCallbacks.push(() => {
          try {
            setTimeout(() => {
              const result = onFulfilled(self.value);
              result instanceof Promise ? result.then(resolve, reject) : resolve(result)
            })
          } catch (e) {
            reject(e);
          }
        });
        self.onRejectedCallbacks.push(() => {
          try {
            setTimeout(() => {
              const result = onRejected(self.reason);
              result instanceof Promise ? result.then(resolve, reject) : reject(self.reason);
            })
          } catch (e) {
            reject(e);
          }
        })
      } else if (self.status === FULFILLED) {
        try {
          setTimeout(() => {
            const result = onFulfilled(self.status);
            result instanceof Promise ? result.then(resolve, reject) : resolve(result)
          })
        } catch (e) {
          reject(e);
        }
      } else {
        try {
          setTimeout(() => {
            const result = onFulfilled(self.status);
            result instanceof Promise ? result.then(resolve, reject) : resolve(result)
          })
        } catch (e) {
          reject(e);
        }
      }
    })
  }

  catch (onRejected) {
    return this.then(null, onRejected);
  }

  static resolve (value) {
    // if (value instanceof Promise) return value;
    // else return new Promise((resolve, reject) => resolve(value));
    return value instanceof Promise ? value : new Promise((resolve, reject) => resolve(value));
  }

  static all (promiseArr) {
    const len = promiseArr.length;
    const values = Array(len);
    let count = 0;

    if (len === 0) {
      this.resolve(result);
      return result;
    }

    return new Promise((resolve, reject) => {
      for (let i = 0; i < len; i++) {
        Promise.resolve(promise[i]).then(val => {
          values[i] = val;
          count++;
          if (count === len) resolve(result);
        }).catch(err => {
          reject(err);
        })
      }
    })
  }

  static race (promiseArr) {
    return new Promise((resolve, reject) => {
      promiseArr.forEach(p => {
        Promise.resolve(p).then(
          val => resolve(val),
          err => reject(err)
        )
      })
    })
  }
}
```